AppGDP/urls.py
from django.urls import path
from . import views
from .views import buscar_itens

urlpatterns = [
        path('', views.homepage, name="homepage"),         # Inclui as urls do app blog
        path('login', views.login, name="login"),           # Inclui as urls do app blog
        path('cadastroUsuario', views.cadastroUsuario, name='cadastroUsuario'),
        path('profile', views.profile, name="profile"),       # Inclui as urls do app blog
        path('faq', views.faq, name="faq"),                 # Inclui as urls do app blog
        path('welcomeHomepage', views.welcomeHomepage, name="welcomeHomepage"),   # Inclui as urls do app blog
        path('itens', views.itens, name="itens"),           # Inclui as urls do app blog
        path('adicionar_inventario', views.adicionar_inventario, name="adicionar_inventario"),   # Inclui as urls do app blog
        path('buscar', buscar_itens, name='buscar_itens'),
        path('excluir_inventario/', views.excluir_inventario, name='excluir_inventario'),
        path('update-item/', views.update_item, name='update_item'),
        path('excluir-item/', views.excluir_inventario, name='excluir_inventario'),
        path('update-sala/', views.update_sala, name='update_sala'),
        path('excluir-sala/', views.excluir_sala, name='excluir_sala'),
        path('adicionar-salas/', views.adicionar_salas, name='adicionar_salas'),
        path('buscar-itens-sala', views.buscar_itens_sala, name='buscar_itens_sala'),
        path('salas', views.salas, name='salas'),
        path('buscar-salas', views.buscar_salas, name='buscar_salas'),
        path('logout/', views.logout, name='logout'),

]

AppGDP/forms.py
from django import forms
from .models import Inventario, Sala
from django.core.exceptions import ValidationError


class formCadastroUsuario(forms.Form):
    first_name = forms.CharField(label="Nome", max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label="Sobrenome", max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    user = forms.CharField(label="Usuário", max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="Email", max_length=100, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="Senha", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    sala = forms.CharField(label="Sala", max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    group = forms.ChoiceField(
        label="Grupo", 
        choices=[('Professor', 'Professor'), ('Coordenador', 'Coordenador')], 
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    def clean_sala(self):
        sala_nome = self.cleaned_data['sala']
        try:
            sala = Sala.objects.get(sala=sala_nome)
        except Sala.DoesNotExist:
            raise ValidationError("A sala informada não existe. Por favor, selecione uma sala válida.")
        return sala_nome
    
class FormLogin(forms.Form):
    user = forms.CharField(label="Usuario", max_length=40)
    password = forms.CharField(label="Senha", widget=forms.PasswordInput)

class InventarioForm(forms.ModelForm):
    class Meta:
        model = Inventario
        fields = ['num_inventario', 'denominacao', 'localizacao','sala', 'link_imagem']  

class SalaForm(forms.ModelForm):
    class Meta:
        model = Sala
        fields = ['sala', 'descricao', 'localizacao', 'link_imagem', 'responsavel', 'quantidade_itens']


AppGDP/templates/cadastroUsuario.html
{% extends "index.html" %}
{% load static %}

{% block body %}
{% include "navbarAutenticado.html" %}

<main class="bg-body-l-w">
    <form class="login-form" method="POST" action="{% url 'cadastroUsuario' %}">
        {% csrf_token %}
        <h1 class="titleLogin">Cadastro</h1>

        <div class="input-group ig1">
            <label for="id_first_name"><b>Nome</b></label>
            <div class="input-container">
                {{ form.first_name }}
            </div>
        </div>

        <div class="input-group ig1">
            <label for="id_last_name"><b>Sobrenome</b></label>
            <div class="input-container">
                {{ form.last_name }}
            </div>
        </div>

        <div class="input-group ig1">
            <label for="id_user"><b>Usuário</b></label>
            <div class="input-container">
                {{ form.user }}
            </div>
        </div>

        <div class="input-group ig1">
            <label for="id_email"><b>Email</b></label>
            <div class="input-container">
                {{ form.email }}
            </div>
        </div>

        <div class="input-group ig2">
            <label for="id_password"><b>Senha</b></label>
            <div class="input-container">
                {{ form.password }}
            </div>
        </div>

        <!-- Sala -->
         <div class="input-group ig1">
            <label for="id_sala"><b>Sala</b></label>
            <div class="input-container">
                {{ form.sala }}
            </div>
        </div>

        <div class="input-group ig1">
            <label for="id_group"><b>Grupo</b></label>
            <div class="input-container">
                {{ form.group }}
            </div>
        </div>

        <button type="submit" class="btn-login">Cadastrar</button>
    </form>
</main>
{% endblock %}

AppGDP/templates/faq.html
{% extends "index.html" %}
{% load static %}

{% block body %}

{% include "navbar.html" %}
{% include "vectorFormas.html" %}
<div class="accordion">
    <div class="accordion-item">
        <div class="accordion-item-title" onclick="toggleAccordion(this)">
            <span class="icon">+</span>
            O que é o gerenciamento de patrimônios no SENAI?
        </div>
        <div class="accordion-item-desc">
            O gerenciamento de patrimônios no SENAI envolve a administração e o controle dos bens e ativos físicos da instituição. Isso inclui a identificação, registro, manutenção, e descarte adequado dos patrimônios para garantir sua conservação e utilização eficiente.
        </div>
    </div>
    
    <div class="accordion-item">
        <div class="accordion-item-title" onclick="toggleAccordion(this)">
            <span class="icon">+</span>
            Como os patrimônios são identificados e registrados?
        </div>
        <div class="accordion-item-desc">
            Cada patrimônio do SENAI recebe uma etiqueta com um código único de identificação. Esse código é registrado em um sistema de gerenciamento, onde são armazenadas informações detalhadas sobre o bem, como data de aquisição, localização, valor, e condição atual.
        </div>
    </div>
    
    <div class="accordion-item">
        <div class="accordion-item-title" onclick="toggleAccordion(this)">
            <span class="icon">+</span>
            Como é feita a manutenção dos patrimônios?
        </div>
        <div class="accordion-item-desc">
            A manutenção dos patrimônios no SENAI é realizada de forma preventiva e corretiva. Equipamentos e máquinas recebem manutenção regular para evitar falhas, e reparos são feitos sempre que necessário para garantir que os patrimônios permaneçam operacionais e em boas condições.
        </div>
    </div>
    
    <div class="accordion-item">
        <div class="accordion-item-title" onclick="toggleAccordion(this)">
            <span class="icon">+</span>
            Qual é a importância do gerenciamento de patrimônios?
        </div>
        <div class="accordion-item-desc">
            Um gerenciamento eficaz de patrimônios garante que os recursos da instituição sejam utilizados de forma eficiente, reduzindo desperdícios e assegurando que todos os bens estejam em bom estado de conservação. Isso também facilita auditorias e relatórios financeiros precisos.
        </div>
    </div>
    
</div>

<script>
    function toggleAccordion(element) {
        const desc = element.nextElementSibling;
        const icon = element.querySelector('.icon');

        if (desc.style.maxHeight) {
            desc.style.maxHeight = null;
            desc.style.opacity = 0;
            icon.textContent = "+";
        } else {
            desc.style.maxHeight = desc.scrollHeight + "px";
            desc.style.opacity = 1;
            icon.textContent = "-";
        }
    }
</script>

{% endblock %}

AppGDP/templates/homepage.html
{% extends "index.html" %}
{% load static %}

{% block body %}

{% include "navbar.html" %}
{% include "vectorFormas.html" %}
<div class="itensHomepage">
    <div class="textsHomepage">
        <p class="subtitlesHomepage">Gerenciamento de patrimônios</p>
        <div id="svg-container">
            <h1 class="titleHomepage">Senai Admin</h1>
        </div>
        <p class="subtitlesHomepage2">Caso já tenha um usuário, faça login para acessar o site</p>
        <a href="login" class="TransparentBlackButton-component">Entrar</a>
            
        

    </div>
    
    <div class="iconHomepage">
        <img src="{% static 'img/ImageIcon.png' %}" alt="ImageIcon" class="ImageIcon-component">
    </div>
</div>  
{% endblock %}

AppGDP/templates/itens.html
{% extends "index.html" %}
{% load static %}

{% block body %}
{% include "navbarAutenticado.html" %}

<main class="bg-body-i-w">

    <div class="allItensContainerSearch">
        <div class="search-container">
            <form id="searchForm" method="GET" action="{% url 'buscar_itens' %}">
                <div class="search-container">
                    <button type="submit">
                        <span class="material-symbols-outlined" id="iconItens">search</span>
                    </button>
                    <input class="input-itens" type="text" name="q" id="searchInput"
                        placeholder="Buscar por número de inventário...">
                </div>
            </form>

            <button onclick="openModal('modalFiltro')">
                <span class="material-symbols-outlined" id="iconItens">filter_list</span>
            </button>

            {% if is_coordenador %}
            <button class="add-button" onclick="openModal('modalAddItem')">
                <span class="material-symbols-outlined" id="iconItens">add_circle</span>
                <p class="add-text">Adicionar</p>
            </button>
            {% endif %}
        </div>
    </div>

    <div class="items-container">
        {% for item in inventario %}
        <div class="item-card"
            onclick="openItemModal('{{ item.denominacao }}', '{{ item.num_inventario }}', '{{ item.link_imagem }}', '{{ item.localizacao }}', '{{ item.sala }}', '{{ item.responsavel }}')">
            <div class="bg-img">
                <img src="{{ item.link_imagem }}" alt="{{ item.denominacao }}">
            </div>
            <div class="inf">
                <h3>{{ item.denominacao }}</h3>
                <p>Inventário: {{ item.num_inventario }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- Modal de excluir -->


    <!-- Modal de Visualização do Item -->

    <div id="modalItem" class="modal">
        <div class="modal-content">
            <button type="button" class="btn-close" onclick="closeModal('modalItem')"><span class="material-symbols-outlined">
                close
                </span></button>
            <h2 class="adicionarH2Itens">Informações</h2>
            <form id="itemForm" method="POST" action="{% url 'update_item' %}">
                {% csrf_token %}
                <label for="denominacaoInput">Denominação:</label>
                <input type="text" id="denominacaoInput" name="denominacao" value="" readonly>

                <label for="numInventarioInput">Número de Inventário:</label>
                <input type="text" id="numInventarioInput" name="numInventario" value="" readonly>

                <label for="localizacaoInput">Localização: </label>
                <input type="text" id="localizacaoInput" name="localizacao" value="" readonly>

                <label for="salaInput">Sala:</label>
                <input type="text" id="salaInput" name="sala" value="" readonly>

                <label for="imagemInput">Imagem:</label>
                <input type="text" id="imagemInput" name="imagem" value="" readonly>

                <label for="responsavelInput">Responsável:</label>
                <input type="text" id="responsavelInput" name="responsavel" value="" readonly>
                {% if is_coordenador %}
                <div class="modal-actions">
                    <button type="button" id="editButton" class="editButton" onclick="enableEdit()">Editar</button>
                    <button type="submit" id="saveButton" class="editButton" style="display:none;">Salvar</button>

                    <button type="button" class="btn-delete" onclick="confirmDelete()">Excluir</button>
                </div>
                {% endif %}
            </form>
        </div>
    </div>

    <!-- Modal de Filtros -->
    <div id="modalFiltro" class="modal">
        <div class="modal-content">
            <button type="button" class="btn-close" onclick="closeModal('modalFiltro')"><span class="material-symbols-outlined">
                close
                </span></button>
            <h2>Filtrar Itens</h2>

            <!-- Filtro por Ordem Alfabética -->
            <form id="filtroAlfabeticoForm" method="GET" action="{% url 'buscar_itens' %}">
                <label for="ordem">Ordenar por:</label>
                <select name="ordem" id="ordem">
                    <option value="A-Z">A-Z</option>
                    <option value="Z-A">Z-A</option>
                </select>
                <button type="submit">Aplicar</button>
            </form>

            <!-- Filtro por Sala -->
            <form id="filtroSalaForm" method="GET" action="{% url 'buscar_itens' %}">
                <label for="sala">Filtrar por Sala:</label>
                <input type="text" name="sala" id="sala" placeholder="Digite o nome da sala">
                <button type="submit">Aplicar</button>
            </form>
        </div>
    </div>



    <!-- Modal de Adicionar Item -->
    <div id="modalAddItem" class="modal">
        <div class="modal-content">
            <button type="button" class="btn-close" onclick="closeModal('modalAddItem')"><span class="material-symbols-outlined">
                close
                </span></button>
            <h2 class="adicionarH2Itens">Adicionar Item</h2>
            <form id="addItemForm" method="POST" action="{% url 'adicionar_inventario' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="modal-actions">
                    <button type="submit" class="btn-add">Adicionar</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Modal de Confirmação -->
    <div id="modalConfirmation" class="modal-confirmation">
        <div class="modal-content-confirmation">
            <h2>Item Adicionado!</h2>
            <p>O item foi adicionado com sucesso ao inventário.</p>
            <button class="btn-close-confirmation" onclick="closeConfirmation()">Fechar</button>
        </div>
    </div>

    <script>
        function openModal(modalId) {
            document.getElementById(modalId).style.display = 'block';
        }

        function closeModal(modalId) {
            document.getElementById(modalId).style.display = 'none';
        }

        window.onclick = function (event) {
            if (event.target.classList.contains('modal')) {
                event.target.style.display = "none";
            }
        }

        function enableEdit() {
            // Torna os campos editáveis
            document.getElementById("denominacaoInput").removeAttribute("readonly");
            document.getElementById("numInventarioInput").removeAttribute("readonly");
            document.getElementById("localizacaoInput").removeAttribute("readonly");
            document.getElementById("salaInput").removeAttribute("readonly");
            document.getElementById("imagemInput").removeAttribute("readonly");
            document.getElementById("responsavelInput").removeAttribute("readonly");

            // Exibe o botão de salvar e oculta o botão de editar
            document.getElementById("editButton").style.display = "none";
            document.getElementById("saveButton").style.display = "inline-block";

            // Altera o action do formulário para o URL de atualização (edição)
            document.getElementById("itemForm").action = "{% url 'update_item' %}";
        }

        function confirmDelete() {
            // Confirmação simples antes de excluir
            if (confirm("Tem certeza de que deseja excluir este item?")) {
                // Altera o action do formulário para o URL de exclusão
                document.getElementById("itemForm").action = "{% url 'excluir_inventario' %}";
                document.getElementById("itemForm").submit();
            }
        }


        function saveChanges() {
            const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value; // Obtém o token CSRF
            const formData = {
                denominacao: document.getElementById("denominacaoInput").value,
                numInventario: document.getElementById("numInventarioInput").value,
                localizacao: document.getElementById("localizacaoInput").value,
                sala: document.getElementById("salaInput").value,
                responsavel: document.getElementById("responsavelInput").value,
                imagem: document.getElementById("imagemInput").value,
            };

            // Faz uma requisição AJAX para enviar os dados ao servidor
            fetch('/update-item/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrfToken // Adiciona o token CSRF
                },
                body: JSON.stringify(formData)
            })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        alert('Item atualizado com sucesso!');
                    } else {
                        alert('Erro ao atualizar o item.');
                    }
                })
                .catch(error => console.error('Erro:', error));

            // Alterna novamente os botões
            document.getElementById("editButton").style.display = "inline-block";
            document.getElementById("saveButton").style.display = "none";

            // Desativa os campos de input
            document.getElementById("denominacaoInput").setAttribute("readonly", true);
            document.getElementById("numInventarioInput").setAttribute("readonly", true);
            document.getElementById("localizacaoInput").setAttribute("readonly", true);
            document.getElementById("salaInput").setAttribute("readonly", true);
            document.getElementById("responsavelInput").setAttribute("readonly", true);
            document.getElementById("imagemInput").setAttribute("readonly", true);
        }

        function openItemModal(denominacao, numInventario, linkImagem, localizacao, sala, responsavel) {
            document.getElementById('denominacaoInput').value = denominacao;
            document.getElementById('numInventarioInput').value = numInventario;
            document.getElementById('imagemInput').value = linkImagem;
            document.getElementById('localizacaoInput').value = localizacao;
            document.getElementById('salaInput').value = sala
            document.getElementById('responsavelInput').value = responsavel;


            openModal('modalItem');
        }

        function openModal(modalId) {
            document.getElementById(modalId).style.display = 'block';
        }

        function closeModal(modalId) {
            document.getElementById(modalId).style.display = 'none';
        }

        window.onclick = function (event) {
            if (event.target.classList.contains('modal')) {
                event.target.style.display = "none";
            }
        }

        function openConfirmation() {
            document.getElementById('modalConfirmation').style.display = 'block';
        }

        function closeConfirmation() {
            document.getElementById('modalConfirmation').style.display = 'none';
            window.location.href = "{% url 'itens' %}";
        }

        document.getElementById('addItemForm').addEventListener('submit', function (event) {
            event.preventDefault();
            const formData = new FormData(this);

            fetch("{% url 'adicionar_inventario' %}", {
                method: 'POST',
                body: formData,
            })
                .then(response => {
                    if (response.ok) {
                        closeModal('modalAddItem');
                        openConfirmation();
                    } else {
                        alert("Erro ao adicionar o item.");
                    }
                })
                .catch(error => {
                    console.error("Erro:", error);
                });
        });
    </script>

</main>
{% endblock %}

AppGDP/templates/login.html
{% extends "index.html" %}
{% load static %}

{% block body %}
{% include "navbar.html" %}
{% include "vectorFormas.html" %}
<main class="bg-body-l-w">
    <form class="login-form" method="POST" action="{% url 'login' %}">
        {% csrf_token %}
        <h1 class="titleLogin">Login</h1>

        <div class="input-group ig1">
            <label for="id_user"><b>Usuário</b></label>
            <div class="input-container">
                {{ form.user }}
            </div>
        </div>

        <div class="input-group ig2">
            <label for="id_password"><b>Senha</b></label>
            <div class="input-container">
                {{ form.password }}

            </div>
        </div>

        <button type="submit" class="btn-login">Entrar</button>

        
    </form>
</main>
{% endblock %}

AppGDP/templates/profile.html
{% extends "index.html" %}
{% load static %}

{% block body %}

{% include "navbarAutenticado.html" %}
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<div class="Profile-Body">
    <div class="container-profile">
        <img src="{% static 'img/ProfileAvatar.png' %}" alt="Avatar" class="Avatar">

        <div class="sub-container-profile">
            <form method="POST" action="{% url 'profile' %}">
                {% csrf_token %}
                
                <!-- Campo de Email -->
                <div class="profile-item">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" value="{{ email }}" disabled required>
                    <span class="material-symbols-outlined edit-icon" id="edit-icons" style="color: white;" onclick="openModal('emailModal')"> edit </span>
                </div>

                <!-- Campo de Nome -->
                <div class="profile-item">
                    <label for="first_name">Nome</label>
                    <input type="text" id="first_name" name="first_name" value="{{ first_name }}" disabled required>
                    <span class="material-symbols-outlined edit-icon" id="edit-icons" style="color: white;" onclick="openModal('emailModal')"> edit </span>
                </div>

                <!-- Campo de Sobrenome -->
                <div class="profile-item">
                    <label for="last_name">Sobrenome</label>
                    <input type="text" id="last_name" name="last_name" value="{{ last_name }}" disabled required>
                    <span class="material-symbols-outlined edit-icon" id="edit-icons" style="color: white;" onclick="openModal('emailModal')"> edit </span>
                </div>

                <!-- Campo de ID -->
                <div class="profile-item">
                    <label for="id">ID</label>
                    <input type="text" id="id" value="{{ id }}" disabled>
                </div>

                <!-- Campo de Sala -->
                <div class="profile-item">
                    <label for="sala">Sala</label>
                    <input type="text" id="sala" value="{{ sala }}" disabled>
                </div>
            </form>

            <!-- Exibir mensagens de sucesso -->
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>

<!-- Modal para editar o Email -->
<div id="emailModal" class="modal">
    <div class="modal-content">
        <span class="close-modal-profile" onclick="closeModal('emailModal')">&times;</span>
        <h2>Editar Email</h2>
        <form method="POST" action="{% url 'profile' %}">
            {% csrf_token %}
            <label for="modalEmail">Novo Email:</label>
            <input type="email" id="modalEmail" name="email" value="{{ email }}" required>
            <button type="submit">Salvar</button>
        </form>
    </div>
</div>

<!-- Modal para editar o Nome -->
<div id="nameModal" class="modal">
    <div class="modal-content">
        <span class="close-modal-profile" onclick="closeModal('nameModal')">&times;</span>
        <h2>Editar Nome</h2>
        <form method="POST" action="{% url 'profile' %}">
            {% csrf_token %}
            <label for="modalName">Novo Nome:</label>
            <input type="text" id="modalName" name="first_name" value="{{ first_name }}" required>
            <button type="submit">Salvar</button>
        </form>
    </div>
</div>

<!-- Modal para editar o Sobrenome -->
<div id="lastNameModal" class="modal">
    <div class="modal-content">
        <span class="close-modal-profile" onclick="closeModal('lastNameModal')">&times;</span>
        <h2>Editar Sobrenome</h2>
        <form method="POST" action="{% url 'profile' %}">
            {% csrf_token %}
            <label for="modalLastName">Novo Sobrenome:</label>
            <input type="text" id="modalLastName" name="last_name" value="{{ last_name }}" required>
            <button type="submit">Salvar</button>
        </form>
    </div>
</div>

<!-- JavaScript para abrir e fechar a modal -->
<script>
    function openModal(modalId) {
        var modal = document.getElementById(modalId);
        modal.style.display = "flex";  // Define 'flex' para centralizar a modal
    }

    function closeModal(modalId) {
        var modal = document.getElementById(modalId);
        modal.style.display = "none";
    }

    // Fecha a modal se clicar fora dela
    window.onclick = function(event) {
        var emailModal = document.getElementById('emailModal');
        var nameModal = document.getElementById('nameModal');
        var lastNameModal = document.getElementById('lastNameModal');

        if (event.target == emailModal) {
            emailModal.style.display = "none";
        }
        if (event.target == nameModal) {
            nameModal.style.display = "none";
        }
        if (event.target == lastNameModal) {
            lastNameModal.style.display = "none";
        }
    }
</script>

{% endblock %}